### ISSUE TITLE
Interaction spacing 

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/ucsb-izc#3] opened 2020-02-05 22:28 UTC
@jhpoelen From my report I found that whitespace for interactions is making a difference.

Not indexed
visitsFlowersOf:Eschscholzia californica
visitsFlowersOf : Lupinus succulentus

Indexed
visitsFlowersOf: Phallia

**Comment by jhpoelen** [comment] 2020-02-05 23:39
Weird. 

I just ran ```elton review > review.tsv``` after cloning https://github.com/globalbioticinteractions/ucsb-izc and found:

```
$ cat review.tsv | grep "visitsFlowersOf:Eschscholzia californica" | cut -f15 | jq ' .context | .sourceTaxonName,.interactionTypeName,.interactionTypeId,.targetTaxonName'
"Coccinellidae"
"visitsflowersof"
"http://purl.obolibrary.org/obo/RO_0002622"
"Eschscholzia californica"
```

Similarly,

```
$ cat review.tsv | grep "visitsFlowersOf : Lupinus succulentus" | cut -f15 | jq ' .context | .sourceTaxonName,.interactionTypeName,.interactionTypeId,.targetTaxonName'
"Heleomyzidae"
"visitsflowersof"
"http://purl.obolibrary.org/obo/RO_0002622"
"Lupinus succulentus"
"Heleomyzidae"
"visitsFlowersOf"
"http://purl.obolibrary.org/obo/RO_0002622"
"Lupinus succulentus"
```

and

```
$ cat review.tsv | grep "visitsFlowersOf: Phallia" | cut -f15 | jq ' .context | .sourceTaxonName,.interactionTypeName,.interactionTypeId,.targetTaxonName'
"Apidae"
"visitsflowersof"
"http://purl.obolibrary.org/obo/RO_0002622"
"Phallia"
```

So, it appears that all examples you provided were able to be indexed. Please let me know which version of elton you are using.

**Comment by seltmann** [comment] 2020-02-06 00:20
I just viewed the report from [Travis](https://api.travis-ci.org/v3/job/643718517/log.txt) 

<img width="932" alt="Screen Shot 2020-02-05 at 4 19 00 PM" src="https://user-images.githubusercontent.com/1044474/73895144-6c8e0480-4833-11ea-8f02-afee1f1af005.png">

**Comment by jhpoelen** [comment] 2020-02-06 00:26
Thanks for the details! That report was made 7 days ago using elton v0.7.1 . I hit the "restart build" button on https://travis-ci.org/globalbioticinteractions/ucsb-izc to use the most recent version.

**Comment by jhpoelen** [comment] 2020-02-06 00:29
Now via https://travis-ci.org/globalbioticinteractions/ucsb-izc/jobs/643718517#L243 :

```
[globalbioticinteractions/ucsb-izc] has 35 reviewer note(s):
     17 source taxon name missing
      7 found unsupported interaction type with name: [on]
      6 found unsupported interaction type with name: [under]
      3 found unsupported interaction type with name: [interactswith]
      1 found unsupported interaction type with name: [inside]
      1 found unsupported interaction type with name: [in]
```

**Comment by seltmann** [comment] 2020-02-06 00:38
Great! All of these can be mapped to interactsWith

Question: why is interactswith an unsupported interaction?

**Comment by jhpoelen** [comment] 2020-02-06 00:47
The mapping to native types (e.g., interactsWith) is case sensitive ; ( . Reproduced and fixed for next release.

**Comment by seltmann** [comment] 2020-02-06 00:58
In the data I enter, it is interactsWith. The is getting lowercased somewhere. Perhaps in Darwin Core archive creation.

**Comment by seltmann** [comment] 2020-02-06 00:59
Nope, still interactsWith in the Dwc-A
<img width="888" alt="Screen Shot 2020-02-05 at 4 59 15 PM" src="https://user-images.githubusercontent.com/1044474/73896789-dc52be00-4838-11ea-945b-f8307d8ff6da.png">

**Comment by jhpoelen** [comment] 2020-02-06 01:24
Just found the issue is in GloBI mapping code. Thanks for pointing this out. Changed to ensure that the matching is case insensitive, but the actual original value remains the same.

**Comment by seltmann** [comment] 2020-02-06 01:27
Great! Got one 🐜 🐛

**Comment by jhpoelen** [comment] 2020-02-06 01:42
Nice catch. 

If you agree that the original issue reported (interaction spacing) is not actually an issue, please close this issue.

**Closed as completed** 2020-02-06 01:54 UTC
